name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7,3.8,3.9,3.10.x,3.11]
 
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: make install
      
      # Install Rust dependencies
      - name: Install Rust dependencies
        run: make rust-install

      # Linting
      - name: lint
        run: make lint
      - name: Lint Rust code
        run: make rust-lint
      # Testing
      - name: Test Python code
        run: make test
      - name: Test Rust code
        run: make rust-test
      # Formatting
      - name: Format Python code
        run: make format
      - name: Format Rust code
        run: make rust-format

      - name: deploy
        run: make deploy

      # Run main scripts
      - name: Run main Python script
        run: python main.py
      - name: Run main Rust script
        run: make run-rust

      - name: List files
        run: |
          pwd
          ls -R  

      - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml_pipeline-artifacts
          path: ${{ github.workspace }}/output



